name: deploy-backoffice-frontend

on:
  push:
    paths:
      - backoffice-frontend/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backoffice-frontend # subdirectory
          file: backoffice-frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhysin/backoffice-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop backoffice-frontend
            docker rm -f backoffice-frontend
            docker pull lhysin/backoffice-frontend:latest
            docker run -d -p 8980:80 --name backoffice-frontend \
            -e NODE_ENV=production \
            lhysin/backoffice-frontend:latest
