name: deploy-backoffice-backend

on:
  push:
    paths:
      - backoffice-backend/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

     # - name: Setup Gradle
     #   uses: gradle/gradle-build-action@v2
      #  working-directory: backend

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: backoffice-backend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backoffice-backend # subdirectory
          file: backoffice-backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhysin/backoffice-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop backoffice-backend
            docker rm -f backoffice-backend
            docker pull lhysin/backoffice-backend:latest
            docker run -d -p 8880:8880 --name backoffice-backend \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -e SPRING_PROFILES_ACTIVE=DEVELOPMENT \
            lhysin/backoffice-backend:latest
